### ISSUE TITLE
Add demo inference server

### ISSUE THREAD

**Issue by janvainer2** [janvainer/speedyspeech#15]
**Task:** Create [flask](https://flask.palletsprojects.com/en/1.1.x/) server for speech synthesis with SpeedySpeech.

#### Backend
- [ ] checkout the [add-inference-server](https://github.com/janvainer/speedyspeech/tree/add-inference-server) branch
- [ ] Make `code/server/app.py` script  containing flask APIs containing the following:
```
@app.route('/')
def home():
    # should render frontend page

@app.route('/synthesize',methods=['POST'])
def synthesize():
    # synthesize audio from text and return audio
   # this endpoint expects input text
```
- for processing request input data see [this page](https://www.digitalocean.com/community/tutorials/processing-incoming-request-data-in-flask)

---

- [ ]  Use the following mock object to synthesize random audio noise and test the API.

```
import numpy as np

class SpeedySpeech:
    def __init__(self, sample_rate=22050, bit_depth=16):
        self.sample_rate = 16000
        self.bit_depth = 16

    def synthesize(input_text):
        data = np.random.uniform(-1, 1, self.sample_rate * 5)  # 5 seconds of noise
        data = np.int16(data / np.max( np.abs(data) ) * (2 ** self.bit_depth - 1))
        return data
```

---

- [ ] Make simple `code/server/index.html` file that expects text from user and has a *synthesize* button. Play requested audio in browser.

#### Frontend:

- [ ] Karaoke highlighting
    1. Animated [word highlighting](https://medium.com/engineered-publicis-sapient/creating-immersive-product-experiences-with-audio-and-animated-text-highlighting-in-react-9a88c9b2acd2) with [React](https://reactjs.org/)
    2. Javascript [library ](https://github.com/johndyer/audiosync) with karaoke highlighting - [article](https://j.hn/html5-audio-karoke-a-javascript-audio-text-aligner/) and [visual example](https://j.hn/lab/html5karaoke/)
    3. Another javascript [project](https://github.com/jaketlarson/karaoke-js) (seems simple)
    4. Even simpler karaoke [javascript engine](https://github.com/sk89q/rice-karaoke)
    5. Tutorial for mozzila [popcorn package](https://code.tutsplus.com/articles/a-look-at-popcorn--net-22666)
    6. [Mark.js](https://markjs.io/) library for javascript word level highlighting
